name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8

      - name: Build
        working-directory: pitchy-1.21.1
        run: gradle build --no-daemon --stacktrace

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: pitchy-1.21.1
          path: pitchy-1.21.1/build/libs/*.jar
